### ISSUE TITLE
warn users with large etherpads

### ISSUE THREAD

**Issue by astruck** [mlzdev/ethergroups#11]
when etherpads exceed 10k lines the browser becomes unresponsive. If it is unknown how to fix that, please warn the user at 5k lines and suggest to split up etherpads.

**Comment by mlz-dev** [comment]
hey, this might be an issue in really huge collaborative settings... and is a generic issue of the underlying  ['etherpad'](https://github.com/ether/etherpad-lite) component in opposite of the 'group management' component of this project, for that i would suggest to cross-post to the corresponding ['etherpad-lite'](https://github.com/ether/etherpad-lite/issues) community. 

Best reagards, mlzdev

**Comment by astruck** [comment]
thanks for the clarification
